# Generated by Django 2.0.3 on 2018-04-12 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educportal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academicgroup',
            old_name='academ_group_name',
            new_name='group_name',
        ),
    ]
